### ISSUE TITLE
"Borrow" Hugo's release procedure

### ISSUE THREAD

**Issue by rhagenson** [RHagenson/relped#35]
Hugo has a great method for updating the git tag and cobra `--version` via a cobra command of `<root> release --rel <major.minor.dev>`

I have more than a few times had a disconnect between these two reports of the current version. I do not want the entire procedure as I will still hand-release, but I want a method to bump the CLI version, commit, tag the commit with the same version -- used as `relped release 1.0.0`

**Comment by rhagenson** [comment]
My goodness. I tried all morning to get something like this working via TravisCI on a `relped-ci` copy of this repo and no progress. 

Closest I got to success was:

```yaml
language: go
sudo: false
go:
    - 1.x
env: GO111MODULE=on
before_install:
    - go get github.com/mitchellh/gox
script:
    - go get -t -v ./...
    - go test -v -race ./...
before_deploy:
    - git config --local user.name "Ryan A. Hagenson"
    - git config --local user.email "Ryan.Hagenson@gmail.com"
    - export TRAVIS_TAG=v$(go build && ./relped --version | grep -P -o '(\d+\.)?(\d+\.)?(\*|\d+)')
    - git tag $TRAVIS_TAG
    - gox -os="linux darwin windows" -arch="amd64"
deploy:
    provider: releases
    draft: true
    file_glob: true
    file: relped_*
    on:
        repo: rhagenson/relped-ci
    api_key:
        secure: DJxXpR3wxshzwq39yvwvC/vgHSGwazV23A9yyB7fcrGWAYUs0EAyHWjblYXq5yxolBOX3IEqCwewPCSNpTjACuGwxjdSGaNWrUtkshpjnH96I7WTQQGGI8Prw6gSBg/wZCrCZdMMUFVqr+XBJRl38kBJPJMoBLMTI5qTR2ZYCy5x+1Ni4d7BcfobKBAqqwwChkRFbcN0Telq7pj9jyVd9U/AkFcf/Tf/TksHKyx6gBK99R1UWpEpCQcAOwBEDyvfQOLknbvpke+hZI2mseR7isna4ko6I61ilHJTEeimf0IFferTS4S+peDFHFGrSQirKNrmodAws4zCqMvjDFCZSCADHTUkHefBvqTGiC8Kk/oYui3CMaRzxq3Hf32cBLDBn/lMhZ6oGc+o6f8ygBFMLOtIsEtGCa5rUxDpoFvKeP0FO1R6T7yQKXrtViUCftHyi21/zC1PMqjxo2YGZJR2w6qPagVUbaLYZM2106Bcw2lHk508FkdHtsW1EFyYgKBL4qMsfmwvnEG0RxynpSpYj6GFNAFL5NQxX+SlBcinTiVfo3X0X07uLJx8WyuBy2JDpfTnvqO1MtjDkITN3JjJWKbRCthALhguuGOoj7luxkGqNhyvrLk+5EVK5Qh5ge9/EJB3dF1933+Qc2fj792qvJ1jzkZZV3HHtjt1I4PeT+s=
```

Which generated an empty release called "Draft", but at least it **created** a release in the end. 

It should not be difficult to simply have a CI system use `gox` to build assets and upload those assets as a draft release under the same name as the tag as pulled from `relped --version`

Until such time as I can determine a solution, this issue is effectively closed as it was an ideal, not a necessity.
